name: 'Bun Environment Setup'
description: 'Setup bun and install dependencies'

inputs:
  dependencies_type:
    description: 'Dependencies type to install. Can be "production" or "development"'
    default: 'production'
    required: false
  bun_version:
    description: 'Bun version to setup'
    default: 'latest'
    required: false
  registry_url:
    description: 'Registry url to use'
    default: 'https://registry.npmjs.org'
    required: false

runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun_version }}
        registry-url: ${{ inputs.registry_url }}

    - name: Restore cached dependencies
      uses: actions/cache/restore@v4
      id: cache
      with:
        path: node_modules
        key: dependencies-${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}

    - name: Install bun dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: bun install --frozen-lockfile ${{ inputs.dependencies_type == 'production' && '--production' || '' }}

    - name: Cache dependencies
      uses: actions/cache@v4
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        path: node_modules
        key: dependencies-${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}
