name: "Bun Environment Setup"
description: "Setup bun and install dependencies"

inputs:
  dependencies_type:
    description: 'Specifies the type of dependencies to install. Choose "production" to install only production dependencies, or "development" to include development dependencies as well.'
    default: "production"
    required: false
  bun_version:
    description: 'The version of Bun to set up in the environment. Use "latest" to get the most recent version.'
    default: "latest"
    required: false
  registry_url:
    description: "The URL of the npm registry to use for installing packages. Defaults to the official npm registry."
    default: "https://registry.npmjs.org"
    required: false

runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun_version }}
        registry-url: ${{ inputs.registry_url }}

    - name: Restore cached dependencies
      uses: actions/cache/restore@v4
      id: restore-dependencies-cache
      with:
        path: node_modules
        key: dependencies-${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}

    - name: Install bun dependencies
      if: steps.restore-dependencies-cache.outputs.cache-hit != 'true'
      shell: bash
      run: bun install --frozen-lockfile ${{ inputs.dependencies_type == 'production' && '--production' || '' }}

    - name: Cache dependencies
      uses: actions/cache@v4
      if: steps.restore-dependencies-cache.outputs.cache-hit != 'true'
      with:
        path: node_modules
        key: dependencies-${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}
