name: "Vitest Test Runner"
description: "Runs Vitest tests, with coverage reporting"

inputs:
  package_manager:
    description: 'The package manager to use for running scripts. Options are "npm" or "bun".'
    default: "npm"
    required: false
  github_token:
    description: "The GitHub token to use for reporting test results."
    required: false

runs:
  using: "composite"
  steps:
    - name: Run tests (bun)
      if: inputs.package_manager == 'bun'
      shell: bash
      run: bunx vitest run --coverage --reporter=junit --reporter=default --outputFile=junit.xml

    - name: Run tests (npm)
      if: inputs.package_manager == 'npm'
      shell: bash
      run: npx vitest run --coverage --reporter=junit --reporter=default --outputFile=junit.xml

    - name: Transform JUnit Report
      if: always()
      uses: MeilCli/common-lint-reporter/transformer/junit@v1
      with:
        report_files: "junit.xml"
        github_token: ${{ inputs.github_token }}

    - name: Report Test Results
      if: always()
      uses: MeilCli/common-lint-reporter@v1
      with:
        report_type: "check_run"
        report_to_same_check_run: "true"
        github_token: ${{ inputs.github_token }}
