name: 'Restore Dependency Cache'
description: 'Restores cached dependencies'

runs:
  using: "composite"
  steps:
    - name: Restore cached dependencies
      uses: actions/cache/restore@v4
      with:
        path: node_modules
        key: dependencies-${{ runner.os }}-${{ hashFiles('**/bun.lockb') || hashFiles('**/package-lock.json') }}
        restore-keys: |
          dependencies-${{ runner.os }}-