name: "Restore Dependency Cache"
description: "Restores cached dependencies"

runs:
  using: "composite"
  steps:
    - name: Restore cached dependencies
      uses: actions/cache/restore@v4
      with:
        path: node_modules
        key: dependencies-${{ runner.os }}-${{ hashFiles('package-lock.json', 'bun.lockb') }}-2
