name: "NPM Environment Setup"
description: "Setup node and install dependencies"

inputs:
  dependencies_type:
    description: 'Specifies the type of dependencies to install. Choose "production" to install only production dependencies, or "development" to include development dependencies as well.'
    default: "production"
    required: false
  node_version:
    description: "The version of Node.js to set up in the environment. This ensures compatibility with your project requirements."
    default: "22"
    required: false
  registry_url:
    description: "The URL of the npm registry to use for installing packages. Defaults to the official npm registry."
    default: "https://registry.npmjs.org"
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        registry-url: ${{ inputs.registry_url }}
        node-version: ${{ inputs.node_version }}
        cache: 'npm'

    - name: Restore cached dependencies
      uses: actions/cache/restore@v4
      id: restore-dependencies-cache
      with:
        path: node_modules
        key: dependencies-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/bun.lockb') }}-1

    - name: Install npm dependencies
      if: steps.restore-dependencies-cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci ${{ inputs.dependencies_type == 'production' && '--omit=dev' || '' }}
    - name: Cache dependencies
      uses: actions/cache/save@v4
      if: steps.restore-dependencies-cache.outputs.cache-hit != 'true'
      with:
        path: node_modules
        key: dependencies-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/bun.lockb') }}-1

