name: "Upload to Cloudflare Pages"
description: "Uploads files to Cloudflare Pages"

inputs:
  api_token:
    description: "Cloudflare API token for authentication."
    required: true
  account_id:
    description: "Cloudflare account ID."
    required: true
  project_name:
    description: "Name of the Cloudflare Pages project."
    required: true
  source_path:
    description: "Local path to the dist folder to upload."
    required: false
    default: "dist"
  # TODO: rework this to support envs and not "branches" so aliases can be used
  ref:
    description: "The name of the branch to deploy."
    required: true

runs:
  using: "composite"
  steps:
    - name: Deploy to Cloudflare Pages
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ inputs.api_token }}
        accountId: ${{ inputs.account_id }}
        # TODO: --commit-hash ${{ inputs.sha }}
        command: pages deploy ${{ inputs.source_path }} --project-name=${{ inputs.project_name }} --branch ${{ inputs.ref }}
