name: 'Upload to S3'
description: 'Uploads files to S3'

inputs:
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: true
  aws_region:
    description: 'AWS Region'
    required: false
    default: 'nbg1'
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: true
  endpoint_url:
    description: 'AWS endpoint URL'
    required: false
    default: ''
  path_to_upload:
    description: 'Path to the files to upload'
    required: true
  s3_bucket:
    description: 'S3 bucket name'
    required: true
  target_path:
    description: 'Target path within the S3 bucket'
    required: false
    default: ${{ github.event.repository.name }}

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}
        aws-session-token: ''
        mask-aws-account-id: true

    - name: Set endpoint URL
      if: inputs.endpoint_url != ''
      shell: bash
      run: |
        aws configure set endpoint_url ${{ inputs.endpoint_url }}

    - name: Deploy to S3
      shell: bash
      run: |
        s3cmd sync ${{ inputs.path_to_upload }} s3://${{ inputs.s3_bucket }}/${{ inputs.target_path }} --delete
