name: 'Upload to S3'
description: 'Uploads files to S3'

inputs:
  access_key:
    description: 'AWS Access Key ID'
    required: true
  secret_key:
    description: 'AWS Secret Access Key'
    required: true
  endpoint:
    description: 'AWS endpoint URL'
    required: false
    default: ''
  source_path:
    description: 'Path to the files to upload'
    required: true
  bucket_name:
    description: 'Bucket name'
    required: true
  destination_path:
    description: 'Target path within the S3 bucket'
    required: false
    default: ${{ github.event.repository.name }}

runs:
  using: "composite"
  steps:
    - name: Install s3cmd
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y s3cmd

    - name: Configure s3cmd
      shell: bash
      run: |
        echo "[default]" > ~/.s3cfg
        echo "access_key = ${{ inputs.access_key }}" >> ~/.s3cfg
        echo "secret_key = ${{ inputs.secret_key }}" >> ~/.s3cfg
        echo "host_base = ${{ inputs.endpoint }}" >> ~/.s3cfg
        echo "host_bucket = %(bucket)s.${{ inputs.endpoint }}" >> ~/.s3cfg

    - name: Deploy to S3-compatible storage
      shell: bash
      run: |
        s3cmd sync ${{ inputs.source_path }} s3://${{ inputs.bucket_name }}/${{ inputs.destination_path }} --delete
