name: "Upload to S3"
description: "Uploads files to S3"

inputs:
  access_key:
    description: "AWS access key for authentication."
    required: true
  secret_key:
    description: "AWS secret key for authentication."
    required: true
  endpoint:
    description: "Custom endpoint for S3-compatible storage. Use this if you are not using AWS S3, but a compatible service."
    required: false
    default: ""
  source_path:
    description: "Local path to the files to upload. Ensure this path ends with a slash to correctly sync directories."
    required: true
  bucket_name:
    description: "Name of the S3 bucket where files will be uploaded."
    required: true
  destination_path:
    description: "Path within the S3 bucket where files will be stored. This should end with a slash to maintain directory structure."
    required: false
    default: "${{ github.event.repository.name }}/"

runs:
  using: "composite"
  steps:
    - name: Install s3cmd
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y s3cmd

    - name: Configure s3cmd
      shell: bash
      run: |
        echo "[default]" > ~/.s3cfg
        echo "access_key = ${{ inputs.access_key }}" >> ~/.s3cfg
        echo "secret_key = ${{ inputs.secret_key }}" >> ~/.s3cfg
        echo "host_base = ${{ inputs.endpoint }}" >> ~/.s3cfg
        echo "host_bucket = %(bucket)s.${{ inputs.endpoint }}" >> ~/.s3cfg

    - name: Deploy to S3-compatible storage
      shell: bash
      run: |
        s3cmd sync ${{ inputs.source_path }} s3://${{ inputs.bucket_name }}/${{ inputs.destination_path }} --delete-removed
