name: Build and Deploy a static app

on:
  workflow_call:
    inputs:
      package_manager:
        description: 'The package manager to use for running scripts. Options are "npm" or "bun".'
        default: "npm"
        type: string
        required: false
      build_path:
        description: "The path to the build script."
        default: "dist/"
        type: string
        required: false
      bucket_name:
        required: true
        type: string
        description: "Name of the S3 bucket where files will be uploaded."
      endpoint:
        required: false
        type: string
        description: "Custom endpoint for S3-compatible storage. Use this if you are not using AWS S3, but a compatible service."
      ref:
        required: false
        type: string
        description: "The branch or tag to deploy. Defaults to the current branch."
        default: ${{ github.ref }}
    secrets:
      ACCESS_KEY:
        required: true
        description: "AWS access key for authentication."
      SECRET_KEY:
        required: true
        description: "AWS secret key for authentication."

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: Beuterei/reusable-workflows/.github/actions/npm-environment-setup@main
        if: inputs.package_manager == 'npm'
        with:
          dependencies_type: development
      - uses: Beuterei/reusable-workflows/.github/actions/bun-environment-setup@main
        if: inputs.package_manager == 'bun'
        with:
          dependencies_type: development

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: Beuterei/reusable-workflows/.github/actions/build@main
        with:
          package_manager: ${{ inputs.package_manager }}
          build_path: ${{ inputs.build_path }}

  linting:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: Beuterei/reusable-workflows/.github/actions/restore-dependency-cache@main
      - name: Lint
        uses: Beuterei/reusable-workflows/.github/actions/eslint-runner@main
        with:
          package_manager: ${{ inputs.package_manager }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  testing:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: Beuterei/reusable-workflows/.github/actions/restore-dependency-cache@main
      - name: Test
        uses: Beuterei/reusable-workflows/.github/actions/jest-test-runner@main

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
      - linting
      - testing
    steps:
      - uses: Beuterei/reusable-workflows/.github/actions/restore-build-cache@main
        with:
          build_path: ${{ inputs.build_path }}
      - name: Deploy
        uses: Beuterei/reusable-workflows/.github/actions/upload-to-s3@main
        with:
          access_key: ${{ secrets.ACCESS_KEY }}
          secret_key: ${{ secrets.SECRET_KEY }}
          bucket_name: ${{ inputs.bucket_name }}
          endpoint: ${{ inputs.endpoint }}
          source_path: ${{ inputs.build_path }}
