on:
  workflow_call:
    inputs:
      dist_tag:
        description: NPM dist tag to publish to
        required: true
        type: string
      node_version:
        description: Node version to build on
        default: "22"
        required: false
        type: string
      package_manager:
        default: npm
        description: Package manager to use. Can be 'npm' or 'bun'
        type: string

# TODO: Check and support all downstream inputs

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: Beuterei/reusable-workflows/.github/actions/npm-environment-setup
        if: inputs.package_manager == 'npm'
        with:
          dependencies_type: development
      - uses: Beuterei/reusable-workflows/.github/actions/bun-environment-setup
        if: inputs.package_manager == 'bun'
        with:
          dependencies_type: development
      - name: Update version to include commit hash
        run: npm version "$(npm pkg get version | sed 's/\"//g')"-"$(date +%s)".${{ github.sha }} --allow-same-version --git-tag-version=false --tag-version-prefix=''
      - name: Publish to ${{ inputs.dist_tag }} tag with npm registry
        run: npm publish --tag ${{ inputs.dist_tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
