---
"on":
  workflow_call:
    inputs:
      dist_tag:
        description: NPM dist tag to publish to
        required: true
        type: string
      node_version:
        description: Node version to build on
        default: "18"
        required: false
        type: string
      package_manager:
        default: npm
        description: Package manager to use. Can be 'npm' or 'bun'
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: ./.github/actions/npm-environment-setup
        with:
          package_manager: ${{ inputs.package_manager }}
          node_version: ${{ inputs.node_version }}
          registry_url: https://npm.pkg.github.com
      - name: Update version to include commit hash
        run: npm version "$(npm pkg get version | sed 's/\"//g')"-"$(date +%s)".${{ github.sha }} --allow-same-version --git-tag-version=false --tag-version-prefix=''
      - name: Publish to ${{ inputs.dist_tag }} tag with npm registry
        run: npm publish --tag ${{ inputs.dist_tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
