---
"on":
  workflow_call:
    inputs:
      dist_tag:
        description: NPM dist tag to publish to
        default: latest
        required: false
        type: string
      node_version:
        description: Node version to build on
        default: 18
        required: false
        type: string
    secrets:
      NPM_TOKEN:
        description: NPM token with right access for publishing
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: ${{ steps.environment.outputs.environment }}
      url: https://www.npmjs.com/package/${{ steps.package-name.outputs.package-name }}/v/${{ steps.package-version.outputs.package-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org
          node-version: ${{ inputs.node_version }}
          cache: npm
      - name: Install node dependencies
        run: npm ci
      - name: Update version for non latest tagged versions
        if: inputs.dist_tag != 'latest'
        run: npm version "$(npm pkg get version | sed 's/\"//g')"-"$(date +%s)".${{ github.sha }} --allow-same-version --git-tag-version=false --tag-version-prefix=''
      - name: Get package name
        id: package-name
        run: echo "package-name=$(npm pkg get name)" >> $GITHUB_OUTPUT
      - name: Get package version
        id: package-version
        run: echo "package-version=$(npm pkg get version)" >> $GITHUB_OUTPUT
      - name: Get environment
        id: environment
        run: echo "environment=$(case "${{ inputs.dist_tag }}" in "latest") echo "production";; "next") echo "next";; *) echo "feature";; esac)" >> $GITHUB_OUTPUT
      - name: Publish to ${{ inputs.dist_tag }} tag
        run: npm publish --tag ${{ inputs.dist_tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
