---
"on":
  workflow_call:
    inputs:
      dist_tag:
        description: NPM dist tag to publish to
        default: latest
        required: false
        type: string
      node_version:
        description: Node version to build on
        default: "18"
        required: false
        type: string
      package_manager:
        default: npm
        description: Package manager to use. Can be 'npm' or 'bun'
        type: string
    secrets:
      NPM_TOKEN:
        description: NPM token with right access for publishing
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.dist_tag }}
      url: ${{ steps.package-version-url.outputs.packageVersionUrl }}
    steps:
      - uses: ./.github/workflows/environment-setup
        with:
          package_manager: ${{ inputs.package_manager }}
          node_version: ${{ inputs.node_version }}
      - name: Update version for non latest tagged versions
        if: inputs.dist_tag != 'latest'
        run: npm version "$(npm pkg get version | sed 's/\"//g')"-"$(date +%s)".${{ github.sha }} --allow-same-version --git-tag-version=false --tag-version-prefix=''
      - name: Get version url
        id: package-version-url
        run: echo "packageVersionUrl=https://www.npmjs.com/package/$(npm pkg get name | tr -d '"')/v/$(npm pkg get version | tr -d '"')" >> "$GITHUB_OUTPUT"
      - name: Publish to ${{ inputs.dist_tag }} tag with npm registry
        run: npm publish --tag ${{ inputs.dist_tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
