---
"on":
  workflow_call:
    inputs:
      dist_tag:
        description: NPM dist tag to publish to
        default: latest
        required: false
        type: string
      node_version:
        description: Node version to build on
        default: 18
        required: false
        type: string
    secrets:
      NPM_TOKEN:
        description: NPM token with right access for publishing
        required: true

jobs:
  publish-feature:
    if: inputs.dist_tag != 'latest' && inputs.dist_tag != 'next'
    uses: ./.github/workflows/internal-npm-shared-publish.yml
    with:
      dist_tag: ${{ inputs.dist_tag }}
      node_version: ${{ inputs.node_version }}
    secrets: inherit
    environment:
      name: feature
      url: ${{ steps.package-version-url.outputs.packageVersionUrl }}
  publish:
    if: inputs.dist_tag == 'latest' || inputs.dist_tag == 'next'
    uses: ./.github/workflows/internal-npm-shared-publish.yml
    with:
      dist_tag: ${{ inputs.dist_tag }}
      node_version: ${{ inputs.node_version }}
    secrets: inherit
    environment:
      name: ${{ inputs.dist_tag }}
      url: ${{ steps.package-version-url.outputs.packageVersionUrl }}