---
"on":
  workflow_call:
    inputs:
      node_versions:
        description: "Node versions matrix to test on"
        default: "['16.x', '17.x', '18.x']"
        required: false
        type: "string"
      format_command:
        description: "Format command to run. To disable set to ''"
        default: "npm run format"
        required: false
        type: "string"
      lint_command:
        description: "Lint command to run. To disable set to ''"
        default: "npm run lint"
        required: false
        type: "string"
      build_command:
        description: "Build command to run"
        default: "npm run build"
        required: false
        type: "string"
      test_command:
        description: "Test command to run. To disable set to ''"
        default: "npm run test"
        required: false
        type: "string"

jobs:
  testing:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        node_version: "${{ fromJson(inputs.node_versions) }}"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-node@v3"
        with:
          node-version: "${{ matrix.version }}"
      - run: "npm ci"
      - env:
          LAST_JOB_INDEX_OFFSET: ${{ strategy.job-total}}
        run: echo ::set-env name=LAST_JOB_INDEX::$(($LAST_JOB_INDEX_OFFSET-1))
      - if: "github.event.inputs.format_command != '' && strategy.job-index == env.LAST_JOB_INDEX"
        run: "${{ github.event.inputs.format_command }}"
      - if: "github.event.inputs.lint_command != '' && strategy.job-index == env.LAST_JOB_INDEX"
        run: "${{ github.event.inputs.lint_command }}"
      - run: "${{ github.event.inputs.build_command }}"
      - if: "github.event.inputs.test_command != ''"
        run: "${{ github.event.inputs.test_command }}"
