name: 'Node QA Testing'
description: 'Runs QA testing with Node.js supporting both Bun and npm'

# TODO: Add coverage support
# TODO: Use Eslint
# TODO: Split into separate "tooling" actions
inputs:
  format_script:
    description: 'Format script to run. Disabled by default'
    required: false
    default: ''
  lint_script:
    description: 'Lint script to run. To disable set to '''
    required: false
    default: 'lint'
  package_manager:
    description: 'Package manager to use. Can be "npm" or "bun"'
    default: 'npm'
    required: false
  test_script:
    description: 'Base test script to run. To disable set to '''
    required: false
    default: 'test:cov'

runs:
  using: "composite"
  steps:
    - name: Check formatting
      if: inputs.format_script != ''
      shell: bash
      run: ${{ inputs.package_manager }} run ${{ inputs.format_script }}

    - name: Check linting
      if: inputs.lint_script != ''
      shell: bash
      run: ${{ inputs.package_manager }} run ${{ inputs.lint_script }}

    - name: Run tests
      if: inputs.test_script != ''
      shell: bash
      run: ${{ inputs.package_manager }} run ${{ inputs.test_script }}
