name: "ESLint Runner"
description: "Runs ESLint on the codebase"

inputs:
  package_manager:
    description: 'The package manager to use for running scripts. Options are "npm" or "bun".'
    default: "npm"
    required: false
  github_token:
    description: "The GitHub token to use for reporting lint results."
    required: false

runs:
  using: "composite"
  steps:
    - name: Run ESLint (bun)
      if: inputs.package_manager == 'bun'
      shell: bash
      run: bunx eslint . --cache --cache-location .eslintcache --output-file eslint_report.json --format json

    - name: Run ESLint (npm)
      if: inputs.package_manager == 'npm'
      shell: bash
      run: npx eslint . --cache --cache-location .eslintcache --output-file eslint_report.json --format json

    - name: Transform ESLint Report
      if: always()
      uses: MeilCli/common-lint-reporter/transformer/eslint@v1
      with:
        report_files: "eslint_report.json"

    - name: Report Lint Results
      if: always()
      uses: MeilCli/common-lint-reporter@v1
      with:
        report_type: "check_run"
        report_to_same_check_run: "true"
        github_token: ${{ inputs.github_token }}
